# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6274af9b2e62a492d0878d55323ead72750f3a1f71fe0390b6906ded12ca385b1d6af92f7ed153b14c9b5e2be64c73bed84ae8e2af902afb939892320a9c734a

test:
  secret_key_base: 6afe61ea782939aecbf834d71648a74cd44a50c15319d8658760fe95f0b29269634cae1a0ba77569bb539b169a859fb609f07d5fee9549b1c3e090badde8c4a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
